CREATE TABLE "users" ("id" varchar(26),"nickname" varchar(64),"avatar_key" varchar(255),"status" smallint DEFAULT 1,"privacy_agreed_at" timestamptz(3),"privacy_version" varchar(32),"acquired_share_id" varchar(26),"last_login_at" timestamptz(3),"created_at" timestamptz(3),"updated_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE TABLE "user_identities" ("id" varchar(26),"user_id" varchar(26),"provider" varchar(16),"provider_uid" varchar(64),"union_id" varchar(64),"created_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_user_identities_union_id" ON "user_identities" ("union_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_provider_uid" ON "user_identities" ("provider","provider_uid");
CREATE INDEX IF NOT EXISTS "idx_user_identities_user_id" ON "user_identities" ("user_id");
CREATE TABLE "credit_accounts" ("user_id" varchar(26),"daily_free_remaining" bigint NOT NULL,"daily_reset_date" date,"bonus_credits" bigint NOT NULL,"ad_rewards_today" bigint NOT NULL,"updated_at" timestamptz(3),PRIMARY KEY ("user_id"));
CREATE TABLE "credit_ledger" ("id" varchar(26),"user_id" varchar(26),"kind" varchar(16),"bucket" varchar(8),"delta" bigint NOT NULL,"balance_daily_after" bigint NOT NULL,"balance_bonus_after" bigint NOT NULL,"ref_type" varchar(32),"ref_id" varchar(64),"note" varchar(255),"created_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "uk_ledger_ref" ON "credit_ledger" ("kind","ref_type","ref_id");
CREATE INDEX IF NOT EXISTS "idx_credit_ledger_user_id" ON "credit_ledger" ("user_id");
CREATE TABLE "ad_sessions" ("id" varchar(26),"user_id" varchar(26),"ad_unit_id" varchar(64),"status" varchar(16),"reject_reason" varchar(64),"client_is_ended" boolean,"server_verified_at" timestamptz(3),"trans_id" varchar(128),"created_at" timestamptz(3),"claimed_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ad_sessions_trans_id" ON "ad_sessions" ("trans_id");
CREATE INDEX IF NOT EXISTS "idx_ad_sessions_user_id" ON "ad_sessions" ("user_id");
CREATE TABLE "photos" ("id" varchar(26),"user_id" varchar(26),"object_key" varchar(255),"width" bigint NOT NULL,"height" bigint NOT NULL,"bytes" bigint NOT NULL,"sha256" varchar(64),"check_status" varchar(16),"check_result" json,"moderation_status" varchar(16) DEFAULT 'pending',"expires_at" timestamptz(3),"created_at" timestamptz(3),"deleted_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_photos_deleted_at" ON "photos" ("deleted_at");
CREATE INDEX IF NOT EXISTS "idx_photos_sha256" ON "photos" ("sha256");
CREATE INDEX IF NOT EXISTS "idx_photos_user_id" ON "photos" ("user_id");
CREATE TABLE "categories" ("id" varchar(26),"module" varchar(16),"kind" varchar(16),"name" varchar(32),"icon" varchar(64),"cover_key" varchar(255),"desc" varchar(64),"sort" bigint DEFAULT 0,"status" smallint DEFAULT 1,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_categories_module" ON "categories" ("module");
CREATE TABLE "specs" ("id" varchar(26),"category_id" varchar(26),"name" varchar(32),"width_mm" decimal(5,1),"height_mm" decimal(5,1),"width_px" bigint NOT NULL,"height_px" bigint NOT NULL,"dpi" bigint DEFAULT 300,"bg_default" varchar(7),"bg_allowed" json,"crop_rule" json,"source_note" varchar(255),"note" varchar(64),"is_hot" boolean DEFAULT false,"sort" bigint DEFAULT 0,"status" smallint DEFAULT 1,"created_at" timestamptz(3),"updated_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_specs_category_id" ON "specs" ("category_id");
CREATE TABLE "templates" ("id" varchar(26),"module" varchar(16),"category_id" varchar(26),"name" varchar(32),"subtitle" varchar(64),"cover_key" varchar(255),"sample_keys" json,"credit_cost" bigint DEFAULT 1,"gen_config" json,"tags" json,"is_hot" boolean DEFAULT false,"sort" bigint DEFAULT 0,"status" smallint DEFAULT 1,"created_at" timestamptz(3),"updated_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_templates_category_id" ON "templates" ("category_id");
CREATE INDEX IF NOT EXISTS "idx_tpl_list" ON "templates" ("module","status","is_hot","sort");
CREATE TABLE "collections" ("id" varchar(26),"module" varchar(16),"name" varchar(32),"cover_key" varchar(255),"description" varchar(255),"sort" bigint DEFAULT 0,"status" smallint DEFAULT 1,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_collections_module" ON "collections" ("module");
CREATE TABLE "collection_templates" ("collection_id" varchar(26),"template_id" varchar(26),"sort" bigint DEFAULT 0,PRIMARY KEY ("collection_id","template_id"));
CREATE TABLE "banners" ("id" varchar(26),"module" varchar(16),"title" varchar(64),"subtitle" varchar(64),"image_key" varchar(255),"link" json,"sort" bigint DEFAULT 0,"status" smallint DEFAULT 1,"start_at" timestamptz(3),"end_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_banners_module" ON "banners" ("module");
CREATE TABLE "tasks" ("id" varchar(26),"user_id" varchar(26),"idempotency_key" varchar(36),"module" varchar(16),"kind" varchar(16),"spec_id" varchar(26),"template_id" varchar(26),"photo_id" varchar(26),"parent_task_id" varchar(26),"params" json,"status" varchar(16),"stage" varchar(16),"provider" varchar(32),"provider_ref" varchar(128),"work_id" varchar(26),"error_code" varchar(32),"error_message" varchar(255),"cost_cents" bigint DEFAULT 0,"uses_genmodel" boolean DEFAULT false,"credits_consumed" bigint DEFAULT 0,"consume_ledger_id" varchar(26),"refund_ledger_id" varchar(26),"notify_requested" boolean DEFAULT false,"created_at" timestamptz(3),"started_at" timestamptz(3),"finished_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_task_status" ON "tasks" ("status","started_at");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_task_idem" ON "tasks" ("user_id","idempotency_key");
CREATE INDEX IF NOT EXISTS "idx_task_user" ON "tasks" ("user_id","created_at");
CREATE TABLE "works" ("id" varchar(26),"user_id" varchar(26),"task_id" varchar(26),"module" varchar(16),"spec_id" varchar(26),"template_id" varchar(26),"object_key" varchar(255),"thumb_key" varchar(255),"alpha_key" varchar(255),"width" bigint NOT NULL,"height" bigint NOT NULL,"meta" json,"ai_label" boolean DEFAULT false,"moderation_status" varchar(16) DEFAULT 'pending',"created_at" timestamptz(3),"deleted_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_works_deleted_at" ON "works" ("deleted_at");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_works_task_id" ON "works" ("task_id");
CREATE INDEX IF NOT EXISTS "idx_works_user_id" ON "works" ("user_id");
CREATE TABLE "favorites" ("user_id" varchar(26),"template_id" varchar(26),"created_at" timestamptz(3),PRIMARY KEY ("user_id","template_id"));
CREATE TABLE "shares" ("id" varchar(26),"user_id" varchar(26),"type" varchar(16),"module" varchar(16),"template_id" varchar(26),"spec_id" varchar(26),"work_id" varchar(26),"preview_key" varchar(255),"poster_key" varchar(255),"path" varchar(255),"title" varchar(128),"status" varchar(16) DEFAULT 'active',"opens" bigint DEFAULT 0,"last_opened_at" timestamptz(3),"created_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_shares_work_id" ON "shares" ("work_id");
CREATE INDEX IF NOT EXISTS "idx_shares_user_id" ON "shares" ("user_id");
CREATE TABLE "share_opens" ("id" bigserial,"share_id" varchar(26),"opener_user_id" varchar(26),"device_id" varchar(64),"platform" varchar(16),"created_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_share_opens_device_id" ON "share_opens" ("device_id");
CREATE INDEX IF NOT EXISTS "idx_share_opens_share_id" ON "share_opens" ("share_id");
CREATE TABLE "events" ("id" bigserial,"user_id" varchar(26),"name" varchar(48),"props" json,"client_ts" timestamptz(3),"created_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_event_name" ON "events" ("name","created_at");
CREATE TABLE "app_configs" ("key" varchar(64),"value" json,"description" varchar(255),"updated_by" varchar(64),"updated_at" timestamptz(3),PRIMARY KEY ("key"));
CREATE TABLE "admin_users" ("id" varchar(26),"username" varchar(64),"password_hash" varchar(255),"role" varchar(16) DEFAULT 'admin',"status" smallint DEFAULT 1,"last_login_at" timestamptz(3),"created_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_admin_users_username" ON "admin_users" ("username");
CREATE TABLE "audit_logs" ("id" bigserial,"admin_id" varchar(26),"action" varchar(64),"target_type" varchar(32),"target_id" varchar(64),"before" json,"after" json,"ip" varchar(64),"created_at" timestamptz(3),PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_audit_logs_admin_id" ON "audit_logs" ("admin_id");
CREATE TABLE "daily_stats" ("date" date,"module" varchar(16),"template_id" varchar(26) DEFAULT '',"spec_id" varchar(26) DEFAULT '',"tasks_created" bigint DEFAULT 0,"tasks_success" bigint DEFAULT 0,"tasks_failed" bigint DEFAULT 0,"works_saved" bigint DEFAULT 0,"credits_consumed" bigint DEFAULT 0,"credits_refunded" bigint DEFAULT 0,"ad_claims" bigint DEFAULT 0,"cost_cents" bigint DEFAULT 0,PRIMARY KEY ("date","module","template_id","spec_id"));
